"""API pública estável da aplicação RSC.

Consumidores externos, especialmente a camada de apresentação, devem
importar símbolos deste módulo ou diretamente de ``applications.rsc``.
Serviços, repositories, serializers, registry e casos de uso concretos
são detalhes internos de composição.
"""

from .application import RscApplication
from .domain import (
    ActivityScore,
    ActivityStatus,
    DocumentStatus,
    EvidenceStatus,
    RequirementScore,
    RscActivity,
    RscDocument,
    RscEvidence,
    RscProcess,
    RscProcessStatus,
    RscScoreResult,
    RscValidationResult,
    ValidationIssue,
    ValidationSeverity,
)
from .dto import (
    DocumentDiagnostic,
    DocumentHealthStatus,
    DocumentReferenceMode,
    UpdateDocumentReferenceResult,
    VerifyDocumentsResult,
)
from .facade import RscApplicationFacade
from .project_session import RscProjectSession
from .use_cases import (
    ActivityNotFoundError,
    CalculateScoreCommand,
    CreateActivityCommand,
    CreateActivityResult,
    CreateEvidenceCommand,
    CreateEvidenceResult,
    CreateProcessCommand,
    CreateProcessResult,
    DocumentNotFoundError,
    DomainValidationError,
    DuplicateEntityError,
    EvidenceNotFoundError,
    GenerateSummaryCommand,
    InvalidCommandError,
    LoadProjectCommand,
    LoadProjectResult,
    ProcessNotFoundError,
    ProcessSummary,
    RegisterDocumentCommand,
    RegisterDocumentResult,
    RscUseCaseError,
    SaveProjectCommand,
    SaveProjectResult,
    ScoreUseCaseResult,
    SessionDisposedError,
    SummaryUseCaseResult,
    UpdateDocumentReferenceCommand,
    ValidateProcessCommand,
    ValidationUseCaseResult,
    VerifyDocumentsCommand,
)

PUBLIC_API_VERSION = "1.5.1"

__all__ = [
    "PUBLIC_API_VERSION",
    "ActivityNotFoundError",
    "ActivityScore",
    "ActivityStatus",
    "CalculateScoreCommand",
    "CreateActivityCommand",
    "CreateActivityResult",
    "CreateEvidenceCommand",
    "CreateEvidenceResult",
    "CreateProcessCommand",
    "CreateProcessResult",
    "DocumentDiagnostic",
    "DocumentHealthStatus",
    "DocumentNotFoundError",
    "DocumentReferenceMode",
    "DocumentStatus",
    "DomainValidationError",
    "DuplicateEntityError",
    "EvidenceNotFoundError",
    "EvidenceStatus",
    "GenerateSummaryCommand",
    "InvalidCommandError",
    "LoadProjectCommand",
    "LoadProjectResult",
    "ProcessNotFoundError",
    "ProcessSummary",
    "RegisterDocumentCommand",
    "RegisterDocumentResult",
    "RequirementScore",
    "RscActivity",
    "RscApplication",
    "RscApplicationFacade",
    "RscDocument",
    "RscEvidence",
    "RscProcess",
    "RscProcessStatus",
    "RscProjectSession",
    "RscScoreResult",
    "RscUseCaseError",
    "RscValidationResult",
    "SaveProjectCommand",
    "SaveProjectResult",
    "ScoreUseCaseResult",
    "SessionDisposedError",
    "SummaryUseCaseResult",
    "UpdateDocumentReferenceCommand",
    "UpdateDocumentReferenceResult",
    "ValidateProcessCommand",
    "ValidationIssue",
    "ValidationSeverity",
    "ValidationUseCaseResult",
    "VerifyDocumentsCommand",
    "VerifyDocumentsResult",
]
