"""Contratos de infraestrutura da camada de casos de uso RSC."""

from .commands import (
    CalculateScoreCommand,
    CreateActivityCommand,
    CreateEvidenceCommand,
    CreateProcessCommand,
    GenerateSummaryCommand,
    GetActivityCommand,
    GetDocumentCommand,
    GetEvidenceCommand,
    GetProcessCommand,
    ListActivitiesByCriterionCommand,
    ListActivitiesByRequirementCommand,
    ListActivitiesCommand,
    ListDocumentsCommand,
    ListEvidenceByActivityCommand,
    ListEvidenceCommand,
    ListProcessesCommand,
    RemoveDocumentCommand,
    RegisterDocumentCommand,
    ValidateProcessCommand,
)
from .errors import (
    ActivityNotFoundError,
    DocumentNotFoundError,
    DomainValidationError,
    DuplicateEntityError,
    EvidenceNotFoundError,
    InvalidCommandError,
    ProcessNotFoundError,
    RscUseCaseError,
    SessionDisposedError,
)
from .registry import RscUseCaseRegistry
from .process_use_cases import (
    CreateProcessUseCase,
    GetProcessUseCase,
    ListProcessesUseCase,
)
from .document_use_cases import (
    GetDocumentUseCase,
    ListDocumentsUseCase,
    RegisterDocumentUseCase,
    RemoveDocumentUseCase,
)
from .activity_use_cases import (
    CreateActivityUseCase,
    GetActivityUseCase,
    ListActivitiesByCriterionUseCase,
    ListActivitiesByRequirementUseCase,
    ListActivitiesUseCase,
)
from .evidence_use_cases import (
    CreateEvidenceUseCase,
    GetEvidenceUseCase,
    ListEvidenceByActivityUseCase,
    ListEvidenceUseCase,
)
from .validation_scoring_use_cases import (
    CalculateScoreUseCase,
    ValidateProcessUseCase,
)
from .process_summary import ProcessSummary
from .summary_use_case import GenerateSummaryUseCase
from .results import (
    CreateActivityResult,
    CreateEvidenceResult,
    CreateProcessResult,
    RegisterDocumentResult,
    ScoreUseCaseResult,
    SummaryUseCaseResult,
    ValidationUseCaseResult,
    GetDocumentResult,
    GetActivityResult,
    GetEvidenceResult,
    GetProcessResult,
    ListDocumentsResult,
    ListActivitiesResult,
    ListEvidenceResult,
    ListProcessesResult,
    RemoveDocumentResult,
)

__all__ = [
    "ActivityNotFoundError",
    "CalculateScoreCommand",
    "CalculateScoreUseCase",
    "CreateActivityCommand",
    "CreateActivityResult",
    "CreateActivityUseCase",
    "CreateEvidenceCommand",
    "CreateEvidenceResult",
    "CreateEvidenceUseCase",
    "CreateProcessCommand",
    "CreateProcessResult",
    "CreateProcessUseCase",
    "DocumentNotFoundError",
    "DomainValidationError",
    "DuplicateEntityError",
    "EvidenceNotFoundError",
    "GenerateSummaryCommand",
    "GenerateSummaryUseCase",
    "GetDocumentCommand",
    "GetDocumentResult",
    "GetDocumentUseCase",
    "GetActivityCommand",
    "GetActivityResult",
    "GetActivityUseCase",
    "GetEvidenceCommand",
    "GetEvidenceResult",
    "GetEvidenceUseCase",
    "GetProcessCommand",
    "GetProcessResult",
    "GetProcessUseCase",
    "InvalidCommandError",
    "ListDocumentsCommand",
    "ListDocumentsResult",
    "ListDocumentsUseCase",
    "ListActivitiesByCriterionCommand",
    "ListActivitiesByCriterionUseCase",
    "ListActivitiesByRequirementCommand",
    "ListActivitiesByRequirementUseCase",
    "ListActivitiesCommand",
    "ListActivitiesResult",
    "ListActivitiesUseCase",
    "ListEvidenceByActivityCommand",
    "ListEvidenceByActivityUseCase",
    "ListEvidenceCommand",
    "ListEvidenceResult",
    "ListEvidenceUseCase",
    "ListProcessesCommand",
    "ListProcessesResult",
    "ListProcessesUseCase",
    "ProcessNotFoundError",
    "ProcessSummary",
    "RegisterDocumentCommand",
    "RegisterDocumentResult",
    "RegisterDocumentUseCase",
    "RemoveDocumentCommand",
    "RemoveDocumentResult",
    "RemoveDocumentUseCase",
    "RscUseCaseError",
    "RscUseCaseRegistry",
    "ScoreUseCaseResult",
    "SessionDisposedError",
    "SummaryUseCaseResult",
    "ValidateProcessCommand",
    "ValidateProcessUseCase",
    "ValidationUseCaseResult",
]
